name: kics-scan-action
on:
  push:
    branches:
      - main
  workflow:
    - kics-scan-action

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Scan Iac with kics
    - name: run kics Scan
      uses: checkmarx/kics-action@v1.3
      with:
        # scanning all directories
        path: '.'
        ignore_on_exit: results # Just throws an error if the scan fails, not with invalid results
        output_formats: "json,html"
        verbose: true
    # Display the results in json format
    - name: display kics results
      run: |
        cat results.json
    # Upload results after scan
    - uses: actions/upload-artifact@v2
      with:
        name: results-json-${{ github.run_id }}
        path: results/results.json
    - uses: actions/upload-artifact@v2
      with:
        name: results-html-${{ github.run_id }}
        path: results/results.html
